Makefile
Makefile ported from coreos/kube-prometheus :)
/cc @metalmatze
=> *: add basic Makefile

examples/development-minio/deployment.yaml, examples/development-minio/pvc.yaml, examples/development-minio/secret.yaml, examples/development-minio/service.yaml
This will get us started during local development.
/cc @squat
=> Add examples/development-minio

jsonnet/kube-thanos/kube-thanos-receive.libsonnet
=> Add emptyDir to thanos-receive component

jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, jsonnetfile.lock.json, manifests/thanos-querier-deployment.yaml
=> Use improved dnssrv records

README.md, example.jsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-servicemonitors.libsonnet, jsonnet/kube-thanos/kube-thanos-sidecar.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, jsonnetfile.lock.json, manifests/thanos-store-service.yaml
/cc @brancz @aditya-konarde @kakkoyun
=> Create optional ServiceMonitors for querier, store and receive

jsonnet/thanos-mixin/alerts/alerts.libsonnet, jsonnet/thanos-mixin/alerts/querier.libsonnet, jsonnet/thanos-mixin/config.libsonnet, jsonnet/thanos-mixin/mixin.libsonnet
This is a very first draft of 3 alerts I could come up with looking at the Thanos Querier metrics.
/cc @brancz @aditya-konarde @bwplotka
=> Create initial thanos-mixin with querier alerts

jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Adding http ports to the services in #8, I missed updating the references to the ports in the receive components.
This will fix it.
=> Fix remote-write ports after adding http to some services

examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-pvc.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, jsonnetfile.lock.json, manifests/thanos-store-statefulSet.yaml
cc @metalmatze @aditya-konarde @kakkoyun
ran into the same issue as: https://github.com/openshift/telemeter/pull/72
=> Remove empty VolumeClaims from StatefulSets

examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, jsonnetfile.lock.json, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Make all of the ports explicit in the arguments and also declare them
explicitly in the pod.
cc @metalmatze
=>  jsonnet: make ports for querier explicit

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/receive.libsonnet, jsonnetfile.lock.json
=> jsonnet: fix receive file reload alert

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/receive.libsonnet
Recently exposed new metrics https://github.com/thanos-io/thanos/pull/1378/files
=> Add new alert based on config reload issues

dashboards/compact.json, dashboards/overview.json, dashboards/querier.json, dashboards/receive.json, dashboards/rule.json, dashboards/sidecar.json, dashboards/store.json, jsonnet/thanos-mixin/dashboards/compact.libsonnet, jsonnet/thanos-mixin/dashboards/querier.libsonnet, jsonnet/thanos-mixin/dashboards/receive.libsonnet, jsonnet/thanos-mixin/dashboards/rule.libsonnet, jsonnet/thanos-mixin/dashboards/sidecar.libsonnet, jsonnet/thanos-mixin/dashboards/store.libsonnet, jsonnet/thanos-mixin/lib/thanos-grafana-builder/builder.libsonnet, jsonnet/thanos-mixin/lib/thanos-grafana-builder/http.libsonnet
This PR improves UX of error panels.
Fixes #26.
=> Improve error panels

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/receive.libsonnet
Consider multiple jobs.
cc @squat
=> Fix  Thanos Receive config reload alert

examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
We want to at least set some limits. These won't be perfect, but it's a start.
/cc @squat @kakkoyun
=> Set resource requests and limits for containers

jsonnet/thanos-mixin/dashboards/compact.libsonnet, jsonnet/thanos-mixin/dashboards/dashboards.libsonnet, jsonnet/thanos-mixin/dashboards/overview.libsonnet, jsonnet/thanos-mixin/dashboards/querier.libsonnet, jsonnet/thanos-mixin/dashboards/receive.libsonnet, jsonnet/thanos-mixin/dashboards/rule.libsonnet, jsonnet/thanos-mixin/dashboards/sidecar.libsonnet, jsonnet/thanos-mixin/dashboards/store.libsonnet, jsonnet/thanos-mixin/lib/thanos-grafana-builder/http.libsonnet, jsonnet/thanos-mixin/mixin.libsonnet
This PR modifies overview dashboard to only includes included dashboards' overview.
cc @metalmatze @squat
=> Make overview composable

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/querier.libsonnet, jsonnet/thanos-mixin/alerts/receive.libsonnet, jsonnet/thanos-mixin/alerts/sidecar.libsonnet, jsonnet/thanos-mixin/alerts/store.libsonnet
This PR aims to improve the readability of alerts.
=> Improve alerts

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Update the default version to v0.7.0.
Can I get a lgtm @kakkoyun @bwplotka @squat :blush:
=> Update Thanos to v0.7.0

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
=> Use the actual quay.io/thanos/thanos:v0.7.0 image

all.jsonnet, examples/all/manifests/thanos-compactor-deployment.yaml, examples/all/manifests/thanos-compactor-service.yaml, examples/all/manifests/thanos-compactor-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet, jsonnet/kube-thanos/kube-thanos-querier.libsonnet
Add the compactor as additional component to the stack.
/cc @squat @bwplotka @brancz @aditya-konarde @kakkoyun
=> Add the compactor as component to kube-thanos

examples/all/manifests/thanos-compactor-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet
Run the thanos compactor with an emptyDir to write its data to.
/cc @aditya-konarde @squat @bwplotka @brancz
=> Add an emptyDir for the compactor data

examples/all/manifests/thanos-compactor-serviceMonitor.yaml, jsonnet/kube-thanos/kube-thanos-servicemonitors.libsonnet
/cc @aditya-konarde @squat @brancz @bwplotka @kakkoyun
=> Create ServiceMonitor for thanos compactor

jsonnet/kube-thanos/kube-thanos-compactor.libsonnet
Hi there,
I'm pretty sure this is a typo or something for the compactor to reference a different service for health checks.
This results in the compactor not being able to start and will just goes into a crash loop.
=> fix health check referencing different service

dashboards/compact.json, dashboards/overview.json, dashboards/querier.json, dashboards/receive.json, dashboards/rule.json, dashboards/sidecar.json, dashboards/store.json, jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/store.libsonnet, jsonnet/thanos-mixin/dashboards/compact.libsonnet, jsonnet/thanos-mixin/dashboards/querier.libsonnet, jsonnet/thanos-mixin/dashboards/receive.libsonnet, jsonnet/thanos-mixin/dashboards/rule.libsonnet, jsonnet/thanos-mixin/dashboards/sidecar.libsonnet, jsonnet/thanos-mixin/dashboards/store.libsonnet, jsonnet/thanos-mixin/lib/thanos-grafana-builder/builder.libsonnet, jsonnet/thanos-mixin/lib/thanos-grafana-builder/slo.libsonnet
This PR adds simple panel descriptions which act as help texts for the user.
=> Add dashboard panel descriptions

examples/all/manifests/thanos-compactor-statefulSet.yaml
Fixes failing build that introduces by merging #45
=> Re-generate manifest files

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/compact.libsonnet, jsonnet/thanos-mixin/alerts/querier.libsonnet, jsonnet/thanos-mixin/alerts/receive.libsonnet, jsonnet/thanos-mixin/alerts/store.libsonnet, tests.yaml
This PR fixes wrong error ratios discovered on alerts.
=> Fix wrong ratios on alerts

examples/development-minio/deployment.yaml
update  Deployment apiversion of minio to apps/v1
=> update  Deployment apiversion of minio to apps/v1

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-compactor-statefulSet.yaml, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Fixes #34 
This is waiting for upstream Thanos changes to be merged, https://github.com/thanos-io/thanos/pull/1534, https://github.com/thanos-io/thanos/pull/1460, https://github.com/thanos-io/thanos/pull/1537, https://github.com/thanos-io/thanos/pull/1538 and https://github.com/thanos-io/thanos/pull/1540.
=> All missing liveness and readiness probes

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/compact.libsonnet
This PR fixes an alert depends on an out of date metric.
=> Fix compaction alert

examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
This PR reflects the receive changes from latest release 
xref: https://github.com/thanos-io/thanos/pull/1498/files
=> Update renamed flag

.circleci/config.yml, jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/store.libsonnet
This PR,
* fixes incorrect PromQL rule
* adds rule check as a CI step
=> Fix incorrect promQL rule

all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet
People will pretty much get this out of the box :blush: 
https://thanos.io/components/bucket.md/#web
/cc @kakkoyun @brancz @bwplotka
=> Create Thanos bucket component running web UI by default

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/absent.libsonnet, jsonnet/thanos-mixin/alerts/querier.libsonnet, jsonnet/thanos-mixin/alerts/receive.libsonnet, jsonnet/thanos-mixin/alerts/store.libsonnet, jsonnet/thanos-mixin/dashboards/overview.json, jsonnet/thanos-mixin/dashboards/querier.json, jsonnet/thanos-mixin/dashboards/receive.json, jsonnet/thanos-mixin/dashboards/rule.json, jsonnet/thanos-mixin/dashboards/sidecar.json, jsonnet/thanos-mixin/dashboards/store.json, jsonnet/thanos-mixin/lib/thanos-grafana-builder/grpc.libsonnet, jsonnet/thanos-mixin/lib/thanos-grafana-builder/http.libsonnet, jsonnet/thanos-mixin/rules.yaml, jsonnet/thanos-mixin/rules/querier.libsonnet, jsonnet/thanos-mixin/rules/receive.libsonnet, jsonnet/thanos-mixin/rules/store.libsonnet
This PR,
* reduces absent alert trigger offset,
* adjusts store gateway latency quantile threshold,
* considers only server-side errors as errors for alerts and dashboards.
=> Improve alerts and dasbhboards

all.jsonnet, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-servicemonitors.libsonnet, jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/absent.libsonnet
This PR adds manifest files and generators for Rule component.
cc @brancz @bwplotka
=> Add Rule component

examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
Signed-off-by: yeya24 <yb532204897@gmail.com>
=> Add missing service name in rule statefulset

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compactor-statefulSet.yaml, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
=> bump thanos version to 0.9.0

Makefile, README.md
Not sure if this is right - but the instructions don't work when referencing the other repo.
=> Remove references to metalmatze repo

all.jsonnet, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-ruler-service.yaml, examples/all/manifests/thanos-ruler-serviceMonitor.yaml, examples/all/manifests/thanos-ruler-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-ruler.libsonnet, jsonnet/kube-thanos/kube-thanos-servicemonitors.libsonnet
This PR renames Thanos `rule` as `ruler`.
cc @metalmatze @squat  @bwplotka 
xref: https://github.com/thanos-io/thanos/issues/1871
=> Rename Thanos rule -> ruler

examples/all/manifests/thanos-ruler-service.yaml, jsonnet/kube-thanos/kube-thanos-ruler.libsonnet
=> Convert ruler service headless for discovery

examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compactor-statefulSet.yaml, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-ruler-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-ruler.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
This PR adjusts periods and failure thresholds for probes more frequently within the same amount of total time to prevent unnecessary waits.
=> Check probes more frequently within the same amount of total time

.gitignore, Makefile, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compactor-statefulSet.yaml, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-ruler-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-ruler.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Those requests and limits are too specific to the individual environments.
In the future, we can provide an example patch which should make it easier for people to add their specific needs. Let's wait until a bigger refactoring by @brancz landed though.
/cc @kakkoyun @squat @bwplotka
=> Remove resource requests and limits

jsonnet/kube-thanos/kube-thanos-receive.libsonnet
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
=> jsonnet: Append hashring configmap mount rather than replacing

examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet
Bucket web listen on 0.0.0.0:10902 by default. Change bucket port from 8080 to 10902
Signed-off-by: wujie1993 qq594jj@gmail.com
=> jsonnet: fix bucket port

examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
@metalmatze @kakkoyun @squat @bwplotka @krasi-georgiev
=> kube-thanos: Filter emptyDir instead of resetting volumes with PVC

examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
@bwplotka @metalmatze @squat @krasi-georgiev @kakkoyun
=> store: Enable binary index header

examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
@metalmatze @squat @kakkoyun @bwplotka @krasi-georgiev
=> Adapt receive local endpoint to gRPC based endpoint

examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
Let's try this again :)
@bwplotka @kakkoyun @metalmatze @squat @krasi-georgiev
Signed-off-by: Frederic Branczyk <fbranczyk@gmail.com>
=> store: Enable binary index header feature

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
This PR adds a changelog filled with changes for already released versions.
cc @brancz @bwplotka @metalmatze
=> Add a changelog

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
Adds flags for recently introduces features:
- offline deduplication
- block delete delay
*  [x] I added CHANGELOG entry for this change.
* Offline deduplication replica labels flag bf7282085045dfbc7f7b0f284b6e3c6852858fab
* Delete delay flags 0c9bee845fc163be69e6103ef2ff6726b2c3f67b
=> compactor, store gw: Add deduplication replica label flags and delete delay flags

.gitignore, Makefile
* Add convenience actions for dependent tools.
* Execute all the added/changed make actions
=> Improve build tooling

Makefile, jsonnetfile.json, jsonnetfile.lock.json
* Upgrade jsonnet-bundler to `v0.3.1`
* `make vendor generate`
=> Upgrade jsonnet-bundler

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet.yaml
* Update CHANGELOG.
* Bump version.
=> Cut release v0.11.0

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/jsonnetfile.lock.json, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
I did not notice the bump to v0.12.0-rc in the CHANGELOG, should I add this here?
Bump jsonnet to thanos v0.12.0 release.
N/A minor bump from rc. Let me know if I should test it? :)
cc @kakkoyun @metalmatze
=> Bump to release v0.12.0

jsonnet/thanos-mixin/README.md
Fixes dead link.
Clicked on new link, seen it works :)
cc @kakkoyun
=> jsonnet/thanos-mixin/README.md: Fix dead link

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-query-deployment.yaml, jsonnet/kube-thanos/kube-thanos-query.libsonnet
Add patch to allow configuring query timeout.
Added to `all.jsonnet` and it works.
@povilasv @kakkoyun @metalmatze
=> query: Allow configuring query timeout

kustomization.yaml
Added kustomization.yaml 
The manifest is laid out just like for kube-prometheus currently using kube-prometheus kustomization.yaml.
=> Add kustomization to base

CHANGELOG.md, README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
Retrospectively cutting v0.13.0. I'm gonna create another one for v0.14.0
cc @s-urbaniak
=> Cut v0.13.0

CHANGELOG.md, README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
=> Merge v0.13 release branch

CHANGELOG.md, README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
=> Cut v0.14.0

CHANGELOG.md, README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
=> Merge v0.14.0 release branch

examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
* Add configurable `--log.level` flag for all commands.
=> *: Add log level for all commands

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-query-frontend-service.yaml, examples/all/manifests/thanos-query-frontend-serviceMonitor.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/thanos.libsonnet
Signed-off-by: Ben Ye <yb532204897@gmail.com>
This pr adds an initial version of thanos query frontend component.
Also bumps thanos image to latest master.
=> Add Thanos Query Frontend component

CHANGELOG.md, README.md, example.jsonnet, examples/thanos-receive.jsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
=> Cut v0.15.0

jsonnet/kube-thanos/kube-thanos-query.libsonnet
As you can see there are no changes in the examples/all so the output
generated is equal to before.
=> Rewrite the thanos-query component without ksonnet

all.jsonnet, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
Adding rules to the all example too.
=> Rewrite the thanos-receive component without ksonnet

CHANGELOG.md, examples/thanos-receive.jsonnet
=> Cut release-0.16

jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet
=> query-frontend: Add guards for empty cache scenario

all.jsonnet, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-store-statefulSet.yaml
replace `SERCIVE` with `SERVICE`
=> Fix typo for memcached service

examples/all/manifests/store-shard0-service.yaml, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-service.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-service.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/store-shards-serviceMonitor.yaml, jsonnet/kube-thanos/kube-thanos-store-shards.libsonnet
=> store: Fix store shard label

all.jsonnet, examples/all/manifests/receive-hashrings-serviceMonitor.yaml, jsonnet/kube-thanos/kube-thanos-receive-hashrings.libsonnet
=> receive: Add a single service monitor for hashring

examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Follow up for #202 
@kakkoyun @metalmatze
=> jsonnet/kube-thanos: Fix fsGroup position

jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
Address the comment  - https://github.com/observatorium/deployments/pull/389#issuecomment-797358595
/assign @brancz 
Signed-off-by: clyang82 <chuyang@redhat.com>
=> enforce ReadWriteOnce

all.jsonnet, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml
Corrected typo of the word SERVICE
No need.
=> fixed typo in placeholder variable

examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
This makes configuring tracing much more convenient.
Closes #219
=> *: Add host ip env var to all containers

CHANGELOG.md, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Only schedule on linux nodes, due to thanos only providing linux images.
=> .*: Only schedule on linux nodes

all.jsonnet
Signed-off-by: Alexis Letessier <alexis.letessier@gmail.com>
Update dns service discovery links
Test link https://thanos.io/tip/thanos/service-discovery.md/#dns-service-discovery
=> update dns discovery links (#242)

examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-replicate-deployment.yaml, examples/all/manifests/thanos-compact-shard0-statefulSet.yaml, examples/all/manifests/thanos-compact-shard1-statefulSet.yaml, examples/all/manifests/thanos-compact-shard2-statefulSet.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-shard0-statefulSet.yaml, examples/all/manifests/thanos-store-shard1-statefulSet.yaml, examples/all/manifests/thanos-store-shard2-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, manifests/thanos-query-deployment.yaml, manifests/thanos-receive-ingestor-default-statefulSet.yaml, manifests/thanos-receive-router-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Signed-off-by: Prashant Balachandran <pnair@redhat.com>
The earlier PR  https://github.com/thanos-io/kube-thanos/pull/258 missed out some files that had to be generated because of which the build is broken. This PR makes changes to those file.
=> fixing the build by generating files

CHANGELOG.md
Signed-off-by: Matej Gera <matejgera@gmail.com>
Cutting `0.27.0` - there are no changes in comparison to 0.26, but we need this to keep the versions in sync.
=> *: Cut 0.27

CHANGELOG.md
Mentions correct version in changelog after #293.
=> Mention correct version in changelog

examples/all/manifests/thanos-query-deployment.yaml, jsonnet/kube-thanos/kube-thanos-query.libsonnet, manifests/thanos-query-deployment.yaml
This PR contains support for endpoint flag in querier. [Reference](https://github.com/thanos-io/kube-thanos/issues/256)
=> Add support for endpoint flag in querier
