.drone.jsonnet, .drone.yml, Makefile
Cleaning up Makefile:
- use jsonnet 0.13 and use `jsonnetfmt` instead of `jsonnet fmt`
- remove reference to non-existing `test` target
- remove installation of build tools as they are already provided in a container image
- enable go modules (for future :) )
Creating drone CI config based on https://github.com/jsonnet-bundler/jsonnet-bundler/blob/master/.drone.yml and https://github.com/coreos/kube-prometheus/blob/master/.travis.yml. CI should use our `quay.io/coreos/jsonnet-ci` image as this is shipping with all necessary tools.
=> DroneCI config

example.jsonnet, jsonnet/kube-thanos/kube-thanos-pvc.libsonnet, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, jsonnetfile.lock.json, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
In a few recent discussions with @ant31 it became very obvious, that using the `_config` was a mistake I and others ran into writing Kubernetes manifests.
This is a first PR trying to clean up a lot of things.
Only the `$.thanos.variables.image` and `$.thanos.variables.objectStorageConfig` are still some what global (but scoped to the Thanos object) as mutliple components need to reference those.
/cc @squat @brancz @aditya-konarde
=> Don't use global _config object

README.md, all.jsonnet, build.sh, example.jsonnet, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-querier-service.yaml, examples/all/manifests/thanos-querier-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet.yaml
This example is mostly for quality assurance of all components together.
Having this in place will more likely catch a mistake of changing something that's not included in the default example.jsonnet
/cc @brancz @kakkoyun @paulfantom
=> Generate all components to examples/all

examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnetfile.lock.json
Adding this label should fix the issue we currently see:
```
level=warn ts=2019-07-15T11:30:15.59135313Z caller=receive.go:284 component=receive err="failed to sync 3 blocks" uploaded=0
level=info ts=2019-07-15T11:30:45.582197204Z caller=shipper.go:350 component=receive msg="upload new block" id=01DFT3NPXG9ZHMDJ5EES257QBB
level=error ts=2019-07-15T11:30:45.584394983Z caller=shipper.go:317 component=receive msg="shipping failed" block=01DFT3NPXG9ZHMDJ5EES257QBB err="empty external labels are not allowed for Thanos block."
```
=> Add external label to the receive component

jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/querier.libsonnet, jsonnet/thanos-mixin/alerts/receive.libsonnet, jsonnet/thanos-mixin/alerts/store.libsonnet
A few alerts had broken metric names that I fixed. The latency alerts with 1s might be too triggery, relax them for now until we have some data to investigate with.
=> Fix alerts and relax thresholds for latency alerts

examples/all/manifests/thanos-querier-service.yaml, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnetfile.lock.json, manifests/thanos-querier-service.yaml
Currently, the thanos querier service points to canonical ports 10901, and 10902. While 10901 is correct, 10902 is not (it should be 9090).
This fixes it by referencing the named ports `grpc` and `http` in the thanos querier service.
/cc @metalmatze @lilic @paulfantom @squat
=> Thanos querier: fix querier ports

examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-querier-service.yaml, examples/all/manifests/thanos-querier-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/development-minio/deployment.yaml, examples/development-minio/pvc.yaml, examples/development-minio/service.yaml, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, jsonnetfile.lock.json, manifests/thanos-querier-deployment.yaml, manifests/thanos-querier-service.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-statefulSet.yaml
This commit changes the `app: ...` labels on all of the resources
to the new label names specified in:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels.
cc @kakkoyun @metalmatze
=> jsonnet: update 'app' labels

dashboards/overview.json, dashboards/querier.json, jsonnet/thanos-mixin/dashboards/overview.libsonnet, jsonnet/thanos-mixin/dashboards/querier.libsonnet
This PR fixes the query dashboards by using correct metrics.
As @bwplotka pointed it out in another PR's [discussion](https://github.com/thanos-io/thanos/pull/1420#pullrequestreview-275566656), it now uses `http_requests_total` and `http_request_duration_seconds_bucket`.
=> Improve Query dashboards

examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-pvc.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
It's probably nicer to rename the PVC name to `statefulSet.metadata.name + "-data"`. So we end up with `thanos-store-data` instead of `data`.
/cc @brancz @aditya-konarde @kakkoyun @squat
=> Rename Thanos Store PVC and bump size to 50Gi

dashboards/overview.json, dashboards/receive.json, jsonnet/thanos-mixin/alerts.yaml, jsonnet/thanos-mixin/alerts/querier.libsonnet, jsonnet/thanos-mixin/alerts/receive.libsonnet, jsonnet/thanos-mixin/dashboards/receive.libsonnet, jsonnet/thanos-mixin/rules.yaml, jsonnet/thanos-mixin/rules/querier.libsonnet, jsonnet/thanos-mixin/rules/receive.libsonnet
This PR reflects the changes introduced in https://github.com/thanos-io/thanos/pull/1458
=> Remove deprecated metrics

examples/all/manifests/thanos-compactor-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet
This commit removes the empty VolumeClaimTemplate field from the
compactor StatefulSet. This fixes the same issue encountered in
https://github.com/thanos-io/kube-thanos/pull/13 and
https://github.com/openshift/telemeter/pull/72.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
cc @kakkoyun @metalmatze
=> jsonnet/kube-thanos: remove volume claim template

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet, jsonnet/kube-thanos/kube-thanos-pvc.libsonnet, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-servicemonitors.libsonnet, jsonnet/kube-thanos/kube-thanos-sidecar.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
We want to make it easier to configure kube-thanos with common variables like name, namespace, image and replicas.
/cc @s-urbaniak @kakkoyun @squat @brancz
=> Introduce scoped by component configuration

all.jsonnet, examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
This PR fixes the volume mount name in the Thanos receive component to
match the name of the receve PVC. It also changes the path from `tsdb`
to `receive` to match the path used by the Thanos store.
cc @metalmatze 
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
=> jsonnet: use correct volume name for receive

examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive-pvc.libsonnet, jsonnet/kube-thanos/kube-thanos-store-pvc.libsonnet
When using a PVC the volumes in StatefulSets are not needed and so far are `null`. Let's hide them.
/cc @squat @kakkoyun
=> Hide volumes in StatefulSet when null

examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compactor-statefulSet.yaml, examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compactor.libsonnet, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-querier-deployment.yaml, manifests/thanos-store-statefulSet.yaml
This PR,
* adds back liveness probes that are removed with #56 after recent fixes at upstream Thanos,
* add `terminationGracePeriod` to each components' deployment/statefulset.
The default value of grace period in Thanos is [`2m`](https://github.com/thanos-io/thanos/blob/1291d962b2af71e56855c629432004635aaae4b6/cmd/thanos/flags.go#L29), thus `120` in the configuration [[0](https://github.com/thanos-io/thanos/blob/1291d962b2af71e56855c629432004635aaae4b6/cmd/thanos/flags.go#L29)].
For further read, 
[1] https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace
[2] https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
[3] https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html
Signed-off-by: Kemal Akkoyun …
=> Add termination grace period and liveness probes

examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive-pvc.libsonnet, jsonnet/kube-thanos/kube-thanos-store-pvc.libsonnet
This PR reverts changes in #63, to enable the consumer to change statefulset volumes downstream.
This caused by a weird `jsonnet` behaviour, simply one can not make visible an invisible property.
cc @metalmatze 
=> Enable statefulSets volumes to be specified at downstream, revert #63

examples/all/manifests/thanos-ruler-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-ruler.libsonnet
This PR fixes the wrong service query.
So it has to be `http` rather than `grpc`.
> The rule component evaluates Prometheus recording and alerting rules against chosen query API via repeated --query (or FileSD via --query.sd).
ref: https://thanos.io/components/rule.md/
cc @bwplotka @squat @metalmatze
=> Fix service discovery query

examples/all/manifests/thanos-querier-deployment.yaml, jsonnet/kube-thanos/kube-thanos-ruler.libsonnet
We need to de-duplicate the `ruler_replica` label if they exist.
/cc @kakkoyun @bwplotka @squat
=> De-duplicate ruler_replica when using Thanos Ruler

examples/all/manifests/thanos-querier-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-querier.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnetfile.json, manifests/thanos-querier-deployment.yaml
We would prefer if Kubernetes schedules the Receive and Querier Pods to individual nodes.
/cc @kakkoyun @squat @bwplotka @brancz
=> Add host anti-affinity to receive and querier

examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
This will come in handy when we want to do automatic cleanup of PVCs with the thanos-receive-controller.
@metalmatze @squat @bwplotka @kakkoyun @krasi-georgiev
=> jsonnet/kube-thanos: Add app labels to volumeClaimTemplates

jsonnet/kube-thanos/kube-thanos-receive.libsonnet
If replicas (for example in OpenShift templates) is not a number, but a string, then this calculation doesn't work, so it'd be good if we allow it to be overridden.
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
=> kube-thanos: Allow PodDisruptionBudget minAvailable to be overridden

jsonnet/kube-thanos/kube-thanos-receive.libsonnet
This change makes it easier to calculate the maxUnavailable as it only
relies on the replication factor as an input variable instead of
replication factor and replicas.
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
Signed-off-by: Frederic Branczyk <fbranczyk@gmail.com>
=> kube-thanos: PDB change from minAvailable to maxUnavailable

examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
Reverts thanos-io/kube-thanos#97
Turns out we haven't released this in thanos yet :upside_down_face: .
@bwplotka @metalmatze @squat @kakkoyun @krasi-georgiev
=> Revert "store: Enable binary index header"

examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
This PR fixes #102.
ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#container-v1-core
cc @brancz 
=> Add termination message policy to containers

jsonnet/kube-thanos/kube-thanos-compact.libsonnet
While we shouldn't run multiple compactors at once, we still might want
to run 1 or 0 replicas.
Signed-off-by: Matthias Loibl <mail@matthiasloibl.com>
/cc @brancz @kakkoyun 
This blocks https://github.com/observatorium/configuration/pull/244 where we set compact.replicas correctly but it doesn't get picked up...
=> Use tc.config.replicas variable in compact component.

README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
* Upgrade v0.12.0-rc.0
* Remove `--experimental.enable-index-header` since binary index header enabled by default and this flag removed from Thanos.
=> Upgrade v0.12.0-rc.0

CHANGELOG.md, examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Extend shutdown grace period of Thanos receive to 900s (15min). 15min is a reasonably large upper limit, anything larger than that should be sharded out further, to reduce the instance size.
We recently had a service degradation that should have lasted less long as the WAL should have been cut gracefully and not replayed after restart.
I see the number change :slightly_smiling_face: 
@metalmatze @squat @kakkoyun
=> receive: Extend shutdown grace period to 900s

CHANGELOG.md, examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Signed-off-by: Frederic Branczyk <fbranczyk@gmail.com>
Spread receive pods across zones.
Tried the example manifests.
@bwplotka @metalmatze @squat @kakkoyun @krasi-georgiev
=> receive: Use anti-affinity to spread across zones

examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
=> No quotation marks on alert.label-drop

CHANGELOG.md, README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-query-service.yaml, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-serviceMonitor.yaml, manifests/thanos-store-statefulSet.yaml
This PR adds a mixin to enable caching bucket support.
* Add `withCachingBucketMemcached` for Thanos Store to enable caching bucket.
* Rename `withMemcachedIndexCache` to `withIndexCacheMemcached` for consistency.
* Bump version to the one include the feature.
* Local test
=> store: Add mixin to enable caching bucket

examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, jsonnet/kube-thanos/kube-thanos-store.libsonnet
* Use consistent store cache backend type for memcached
Upstream Thanos fix, xref: https://github.com/thanos-io/thanos/pull/2634
=> store: Use consistent store cache backend type for memcached

all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-service.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/thanos-receive.jsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
* Reflect changes introduced in https://github.com/thanos-io/thanos/pull/2613/files
`chunkObjectSizeTTL` -> `chunkObjectAttrsTTL`
* Test with local cluster
=> store: Reflect changes from update caching bucket config

CHANGELOG.md, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
Pod anti affinity for stores.
Validated with kubectl validate against a kind cluster.
=> store: Pod anti affinity to distribute stores across nodes

examples/all/manifests/thanos-bucket-deployment.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet
Signed-off-by: yeya24 <yb532204897@gmail.com>
Now thanos has a `tools` prefix before `bucket`
=> Update bucket web to tools bucket web

examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
The `app.kubernetes.io/instance` label is intended to be set to a value that groups multiple components into one instance, for example an entire thanos stack may be identified by it. This makes performing anti affinity against this value alone problematic, as it means that the scheduler will attempt to perform anti-affinity for all pods in the Thanos stack equally, whereas for availability purposes of the receive component the anti-affinity among them is the important thing.
Generation, and we have applied the same thing for stores already successfully.
@thanos-io/thanos-maintainers
=> receive: Only perform anti affinity against receive pods

examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-store-serviceMonitor.yaml
The instance label is univesally used to refer to an instance in
alerting rules and dashboards. To make it easy to identify in a
Kubernetes environment it's most useful to relabel an identifier of the
pod into the instance label.
Do you think this needs a changelog entry?
Asking @metalmatze to apply this to a cluster as I'm opening this PR :) 
@thanos-io/thanos-maintainers
=> *: Relabel pod reference into instance label

.circleci/config.yml, Makefile, README.md, all.jsonnet, example.jsonnet, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-store-service.yaml, examples/all/manifests/thanos-store-statefulSet-with-memcached.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, examples/extend.jsonnet, examples/extend/thanos-query-deployment.yaml, examples/extend/thanos-query-service.yaml, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-service.yaml, manifests/thanos-store-statefulSet.yaml
Both components are now exposing a function that takes an object as parameters which gets merged with defaults.
The generated Kubernetes objects are returned inside an object like before.
Hopefully this will scope the component's features better and going
forward will make it more obvious what each component supports (by
looking at its defaults at the top, to check what can be passed to it),
the component will even do some safety checks (using assert) on the
merged configuration it'll use and give back some Kubernetes objects.
If there are some limitations that, after discussing the component
shouldn't support, everybody is still able to merge additional features
on top of the generated objects.
/cc @krasi-georgiev @bwplotka
=> Use functions to generate Query & Store deployments

all.jsonnet
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Use the port specified in query service instead of hardcoded 9090.
Changelog is not needed I think since the change is small.
=> Specify the downstreamURL port from service port

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-query-deployment.yaml, jsonnet/kube-thanos/kube-thanos-query.libsonnet
xref: https://github.com/thanos-io/thanos/pull/3010
* Add a new mixin to specify `--query.lookback-delta` flag.
cc @krasi-georgiev
=> querier: Add lookback delta for querier

jsonnet/kube-thanos/kube-thanos-rule.libsonnet
Allow to configured alertmanager in ruler and then enabling me to easily forward alerts from alertmanager:
1. expose `alertmanagersURL` to be able to configure alertmanager url
2. expose `rulesConfig` to be able to configure name and key 
- name: rule configmap name
- key: rule file name
/assign @squat
=> Support configure alertmanager

examples/all/manifests/thanos-query-frontend-deployment.yaml, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
Signed-off-by: Ben Ye <yb532204897@gmail.com>
This flag is renamed from `query-frontend.log_queries_longer_than` to `query-frontend.log-queries-longer-than`
=> Update query frontend flag name

all.jsonnet
Just making sure it's most clear to users why the "all" example exists.
Sadly a README in `examples/all/manifests/` will always be overwritten with each generation.
=> Add notice on all example usage

jsonnet/kube-thanos/kube-thanos-bucket.libsonnet
As you can see there are no changes in the examples/all so the output
generated is equal to before.
=> Rewrite the thanos-bucket component without ksonnet

jsonnet/kube-thanos/kube-thanos-compact.libsonnet
As you can see there are no changes in the examples/all so the output
generated is equal to before.
=> Rewrite the thanos-compact component without ksonnet

jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet
As you can see there are no changes in the examples/all so the output
generated is equal to before.
=> Rewrite the thanos-query-frontend component without ksonnet

all.jsonnet, examples/all/manifests/thanos-receive-podDisruptionBudget.yaml, examples/all/manifests/thanos-receive-service.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
There were some changes in places were the receive component hasn't been
consistent with the other components.
Additionally, I also added PodDisruptionBudget to the examples/all/
=> Rewrite the thanos-receive component without ksonnet

README.md, all.jsonnet, example.jsonnet, examples/thanos-receive.jsonnet, jsonnet/kube-thanos/jsonnetfile.json, jsonnetfile.lock.json
All ksonnet dependencies have been removed.
As a matter of fact there are no dependencies for kube-thanos left.
These are pure jsonnet,JSON,YAML files now.
=> Remove ksonnet

examples/all/manifests/thanos-bucket-service.yaml, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-query-frontend-service.yaml, examples/all/manifests/thanos-receive-service.yaml, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-store-service.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-service.yaml
We want to use the same value for port and targetPort.
At the same time, I refactored to having these high-level config ports objects and the individual Kubernetes components get their values from. This should be a lot cleaner compared to do `ports[0]` in a couple of places too.
/cc @kakkoyun
=> Create high level config for ports that get use by other objects

all.jsonnet, examples/all/manifests/thanos-query-frontend-deployment.yaml, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet
Signed-off-by: Ben Ye <yb532204897@gmail.com>
This pr supersedes #163.
Added new flag configurations for the labels and series middleware of the query frontend.
=> Add new flags and memcached support to query frontend

all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
Add --tracing.config support to all components. The user simply has to specify a `tracing:{}` object with the type for the most part.
=> Add --tracing.config support to all components

jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet
Made a mistake on #171, this fixes the issue.
=> query-frontend: Fix wrongly referred config

CHANGELOG.md, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-store-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
store, query, frontend: add log.format flag
Default to "logfmt", the same as the upstream default.
Also fix bug in which logLevel was not passed to query frontend.
I've tested this in a dev environment (k3d).
=> store, query, frontend: add log.format flag

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-store.libsonnet
store: fix error when bucket cache not used
The default bucketCache is `{}`, which caused a runtime error when
trying to access the `type` field.
I only encountered this error when using `thanos.storeShards()`, not when using `thanos.store()`. I am not sure why this is, the code looks as though it should produce this error in `store()` too, if `config.bucketCache` is unset (and defaults to `{}`).
It looks like https://github.com/thanos-io/kube-thanos/pull/171 fixed a similar problem with query-frontend cache config.
I've tested this locally (in k3d) with no explicit `config.bucketCache`, and one with `type: memcached`.
=> store: fix error when bucket cache not used

examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-store.libsonnet
This flag was removed in v0.17.0 and the compression is enabled by
default
=> Delete the removed flag experimental.enable-index-cache-postings-compression

CHANGELOG.md
Do not keep kube-thanos patch version in sync with Thanos.
=> Fix CHANGELOG for release-0.17 cut

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
**Make cache types case insensitive**
This appears to be the case in thanos itself
(https://github.com/thanos-io/thanos/blob/master/pkg/queryfrontend/config.go#L81
and https://github.com/thanos-io/thanos/blob/master/pkg/store/cache/factory.go#L45).
The thanos docs use upper-case cache types.
Previously, using an upper-case string "MEMCACHED" for memcached caches would work fine, except that the user would not inherit the kube-thanos defaults for memcached configs.
I ran `make generate validate`, and have tried pulling in this branch to a development environment to validate that it works.
=> Make cache types case insensitive

CHANGELOG.md, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Allow configuring `--label` and `--receive.tenant-label-name` flags.
Generation works as expected in committed files.
@kakkoyun
=> receive: Extend configuration for labels

all.jsonnet, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
fix this issue - https://github.com/observatorium/operator/issues/19
=> Reload rules configmap

CHANGELOG.md, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Run each component as non-root user (using the UID that is typically used as the nobody user in most distros).
Closes https://github.com/thanos-io/kube-thanos/issues/141
Validations passing
@kakkoyun
=> *: Run all as non-root

CHANGELOG.md, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Follow up on #200 (thank you @brancz for picking this up!), related to #141.
Set `fsGroup` in the pod security context to a non-root GID.
This is required to make the AWS WebIdentity token file readable for example.
Reference: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration
Running as non-root from the beginning with such settings (arbitrary IDs were only different: UID:1000, fs GID: 2000)
=> *: Set fsGroup when running as non-root

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-sidecar-service.yaml, examples/all/manifests/thanos-sidecar-serviceMonitor.yaml, jsonnet/kube-thanos/kube-thanos-sidecar.libsonnet, jsonnet/kube-thanos/thanos.libsonnet
Add Kubernetes service (and ServiceMonitor) to discover Thanos Sidecar. Expects `podLabelSelector`.
We also use the `kube-prometheus` library which can create a Sidecar service per `Prometheus`, but this means each time a new one is deployed Query needs to be updated. This configuration is meant to be more global, when a `Prometheus` is deployed in a namespace with this service, it is automatically discovered, no need to update Query.
I think this will help with #132.
We have been using this configuration in all our clusters without issues for quite some time.
=> sidecar: Add pod discovery

Makefile
* Enable `kubeval` strict mode to catch misplaced properties and avoid cases like #202 followed by #203:
```
--strict                                Disallow additional properties not in schema
```
* Validate examples (`all.jsonnet`) as well
Tested on the #202 branch:
```
kubeval-v0.0.0-20201005082916-38668c6c5b23 --strict --ignore-missing-schemas manifests/*.yaml
WARN - Set to ignore missing schemas
WARN - manifests/thanos-query-deployment.yaml contains an invalid Deployment (thanos.thanos-query) - fsGroup: Additional property fsGroup is not allowed
PASS - manifests/thanos-query-service.yaml contains a valid Service (thanos.thanos-query)
PASS - manifests/thanos-query-serviceAccount.yaml contains a valid ServiceAccount (thanos.thanos-query)
WARN - …
```
=> ci: Enable kubeval strict mode

CHANGELOG.md, README.md, jsonnet/thanos-mixin/README.md
* Update documentation to refer to `main` branch
=> Use main branch in documentation

examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Part of fix for https://github.com/observatorium/operator/issues/51. Make the securityContext configurable so that we can configure different securityContext to fit for different platform (e.g.: OpenShift) 
Signed-off-by: clyang82 <chuyang@redhat.com>
=> Make securityContext configurable

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet
Allow configuring --label and --refresh flags for the bucket web component.
Generation works as expected in committed files.
=> Bucket Web: Extend configuration for labels and refresh

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-store-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
Add configuration options to configure `--min-time` and `--max-time` in the Thanos store.
Ran generate.
@kakkoyun @metalmatze
=> store: Add min/max time flag configuration

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-query-deployment.yaml, jsonnet/kube-thanos/kube-thanos-query.libsonnet, manifests/thanos-query-deployment.yaml
Enable `--query.auto-downsampling` for query by default.
Generation works as expected in committed files.
=> Query: Enable auto downsampling

CHANGELOG.md, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
Signed-off-by: clyang82 <chuyang@redhat.com>
=> Support configure tsdb.retention and tsdb.block-duration for rule

CHANGELOG.md
Since we are a bit late for the v0.18.0 release, my plan is to only push the CHANGELOG to master and update the manifests in the release branch directly. I would go with the following process for the release branch:
- Cut the release-branch based on e00c4f2 with the following changes https://github.com/thanos-io/kube-thanos/compare/release-0.17...e00c4f2. This include all the changes made before the release of thanos v0.18.0 the 1st of February.
- Cherry-pick changes made to the changelog. Should we also keep the unreleased changes?
- Update manifests
- Tag
Let me know if this sounds good to you.
/cc @kakkoyun
=> Add v0.18.0 CHANGELOG

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-query.libsonnet
- Allow configuring `--web.prefix-header` of query.
Tested locally.
=> Allow configuring `--web.prefix-header` of query.

CHANGELOG.md, all.jsonnet, examples/all/manifests/compact-shard0-service.yaml, examples/all/manifests/compact-shard0-statefulSet.yaml, examples/all/manifests/compact-shard1-service.yaml, examples/all/manifests/compact-shard1-statefulSet.yaml, examples/all/manifests/compact-shard2-service.yaml, examples/all/manifests/compact-shard2-statefulSet.yaml, examples/all/manifests/compact-shards-serviceMonitor.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compact-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-compact-shards.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/thanos.libsonnet
Signed-off-by: ben.ye <ben.ye@bytedance.com>
Fixes #231 
Similar to the store shards, I add shards for compactors.
The difference is that store gateway is sharded by `__block_id`, but compactor needs to be sharded by the external labels of the blocks (e.g. cluster). This should be configured by users.
=> Support compactor hash sharding

examples/all/manifests/compact-shard0-statefulSet.yaml, examples/all/manifests/compact-shard1-statefulSet.yaml, examples/all/manifests/compact-shard2-statefulSet.yaml, examples/all/manifests/store-shard0-statefulSet.yaml, examples/all/manifests/store-shard1-statefulSet.yaml, examples/all/manifests/store-shard2-statefulSet.yaml, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, examples/all/manifests/thanos-query-deployment.yaml, examples/all/manifests/thanos-query-frontend-deployment.yaml, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-deployment.yaml, manifests/thanos-store-statefulSet.yaml
Update nodeSelector to kubernetes.io/os  since beta.kubernetes.io/os deprecated since v1.14 and shows warning in logs
NA
=> jsonnet/manifests/example: Update/generate nodeSelector to kubernetes.io/os instead of beta.kubernetes.io/os

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-bucket-replicate-deployment.yaml, examples/all/manifests/thanos-bucket-replicate-service.yaml, examples/all/manifests/thanos-bucket-replicate-serviceAccount.yaml, examples/development-minio/pvc.yaml, examples/development-minio/service.yaml, jsonnet/kube-thanos/kube-thanos-bucket-replicate.libsonnet, jsonnet/kube-thanos/thanos.libsonnet
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
Add a new bucket replicate component. The libsonnet file is modified based on the bucket.libsonnet file.
We have been using this component in production.
=> add bucket replicate component

CHANGELOG.md, examples/all/manifests/thanos-rule-service.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
* [] Change is not relevant to the end user.
Adds config to allow scraping of the Thanos Ruler config reloader sidecar.
Deployed on minikube, look at the targets page and see thanos ruler with the desired endpoint is `up`.
=> Support scraping config-reloader sidecar for Thanos Ruler

CHANGELOG.md, examples/all/manifests/thanos-compact-service.yaml, examples/all/manifests/thanos-compact-shard0-service.yaml, examples/all/manifests/thanos-compact-shard1-service.yaml, examples/all/manifests/thanos-compact-shard2-service.yaml, jsonnet/kube-thanos/kube-thanos-compact.libsonnet
Fixes #243.
Set `clusterIP: None` in Compact service to support it's use in the StatefulSet `serviceName` field.
Copied pattern from store.
CI passes.
=> compact: make service headless

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-bucket-replicate.libsonnet, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive-router.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
closes: https://github.com/thanos-io/kube-thanos/issues/246
- format the env section of `kube-thanos-store.libsonnet`
- add support for `extraEnv` (adding custom environment variables) to all kube-thanos components
- changelog entry
to test this change I edited the default values for a few components (not all!) and added the following:
```
{
name: 'JAEGER_DISABLED',
value: 'false',
},
{
name: 'JAEGER_SAMPLER_TYPE',
value: 'probabilistic',
},
{
name: 'JAEGER_SAMPLER_PARAM',
value: '0.01',
},
{
name: 'JAEGER_AGENT_HOST',
valueFrom: {
fieldRef: {
fieldPath: 'status.hostIP',
},
},
},
```
I then run `make all` which includes automated verification of validity of generated k8s yaml files. I also eye-balled the generated files in `./examples` and `./manifests` to see if they looked as expected
=> Add extra env vars to all components deployed with kube-thanos

jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
We have this use case as the cluster domain name is not `cluster.local`.
=> Make receiver cluster domain name configurable

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Signed-off-by: Marco llan@redhat.com
=> receiver: make tenant-header of receiver configurable

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
=> support alertmanager configuration and extra volumes for thanos ruler.

README.md, examples/development-minio/deployment.yaml
Running the existing example minio deployment causes the minio pod to crash loop.
I've updated the deployments command accordingly. 
```
$ docker run --entrypoint=whereis minio/minio minio                                                                                   
minio: /opt/bin/minio.sha256sum /opt/bin/minio /opt/bin/minio.minisig
```
=> examples: Update minio command to fix crash looping

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-bucket-deployment.yaml, examples/all/manifests/thanos-bucket-replicate-deployment.yaml, jsonnet/kube-thanos/kube-thanos-bucket-replicate.libsonnet, jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
Signed-off-by: clyang82 <chuyang@redhat.com>
Support custom certificate for the object store. It is part of https://github.com/thanos-io/thanos/issues/4820
Propose to add the following fields in objectStorageConfig:
`tlsSecretName`: tls secret name
`tlsSecretMountPath`: tls secret mount path.
the example thanos object store format can be:
```
config:
bucket: ""
endpoint: ""
insecure: false
put_user_metadata: {}
http_config:
tls_config:
ca_file: "/etc/certs/ca.crt"
cert_file: "/etc/certs/cert.crt"
key_file: "/etc/certs/key.key"
insecure_skip_verify: false
```
so the objectStorageConfig can be:
```    
name: 'thanos-objectstorage',
key: 'thanos.yaml'
tlsSecretName: 'thanos-objectstorage-certs' --- the tls secret needs have the ca.crt/cert.crt/key.key keys.
tlsSecretMountPath: '/etc/certs' …
```
=> Support custom certificate for the object store

CHANGELOG.md, all.jsonnet, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
This PR adds support for running Stateless Rulers using kube-thanos.
- Adds option `remoteWriteConfigFile` to defaults in `kube-thanos-rule.libsonnet`
- Modifies `all.jsonnet` to use newly added option
Tested locally.
=> Support stateless Ruler

CHANGELOG.md, examples/all/manifests/thanos-compact-shard0-statefulSet.yaml, examples/all/manifests/thanos-compact-shard1-statefulSet.yaml, examples/all/manifests/thanos-compact-shard2-statefulSet.yaml, examples/all/manifests/thanos-compact-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-compact-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet
**THIS IS WORK IN PROGRESS**
* Added command line flag `--compact.concurrency` to thanos compact statefulset
* Added command line flag `--downsample.concurrency` to thanos compact statefulset
This change adds the flag `--compact.concurrency` to the thanos compact StatefulSet. This sets the number of goroutines used during compaction. Set this number to any value `X` greater than one, and thanos compact will be fixed to the given number of threads. this feature requires `X` times more CPU and memory to thanos compact as stated on [Resources > Cpu](https://thanos.io/tip/components/compact.md/#cpu). The default is one goroutine.
This change also adds the flag `--downsample.concurrency` to the thanos compact StatefulSet. This sets the number of goroutines used during downsampling. [Resources …
=> Added multithreading support to thanos compact

jsonnet/kube-thanos/kube-thanos-query.libsonnet
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Added deprecated rules field in order to fix prod issue.

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-receive-ingestor.libsonnet, jsonnet/kube-thanos/kube-thanos-receive-router.libsonnet
This PR changes `hashringConfigmapName` to `hashringConfigMapName` to makes things consistent. This fixes an issue where the configmap name was not properly populated on the receive router pod.
I tested this in a development cluster.
=> Change hashringConfigmapName to hashringConfigMapName

jsonnet/kube-thanos/kube-thanos-receive-router.libsonnet, manifests/thanos-receive-router-service.yaml
This PR updates the Thanos Receive router service to include the `routerLabels ` included on other router resources. It also reformats the ports section and adds assertions that also exist for other service port declarations.
I test this in a cluster and verified that it works.
=> Add routerLabels to Receive router service

jsonnet/kube-thanos/kube-thanos-receive-ingestor.libsonnet
This PR enables the Receive ingestor ServiceMonitor if it is enabled by the config flag. It fixes an issue where no ServiceMonitor was created even it was enabled in the configuration.
I tested this out. It does not change default behavior.
=> Create ServiceMonitor for Receive ingestors

CHANGELOG.md, Makefile, examples/all/manifests/thanos-receive-default-podDisruptionBudget.yaml, examples/all/manifests/thanos-receive-region-1-podDisruptionBudget.yaml, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
This PR changes Receive PDB `apiVersion` to `policy/v1` as `policy/v1beta1` is set to be deprecated since K8s v1.21 and will be removed in v1.25 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125.
Currently we get warnings while deploying like,
```
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
- Change Receive PDB to `policy/v1`
- Update kubeconform make target to K8s v1.21
Tested locally.
=> Change Receive PDB to `policy/v1`

CHANGELOG.md, examples/all/manifests/thanos-store-shard0-statefulSet.yaml, examples/all/manifests/thanos-store-shard1-statefulSet.yaml, examples/all/manifests/thanos-store-shard2-statefulSet.yaml, examples/all/manifests/thanos-store-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-store-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-store-statefulSet.yaml
Signed-off-by: Douglas Camata <159076+douglascamata@users.noreply.github.com>
Under heavy load, the 1s default timeout for the Store liveness probe can be often triggered, which leads to Store restarts. This PR makes such timeout configurable.
The default value is 1s, to keep the current behavior, and in affected environments one can increase it.
=> Store: make the liveness probe timeout configurable

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-store-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet
* Allow the configuration of the Store's touched series, series sample, and downloaded bytes limits.
=> Store: allow configuration of series, series sample, and downloaded bytes limits

CHANGELOG.md, examples/all/manifests/thanos-bucket-replicate-deployment.yaml, jsonnet/kube-thanos/kube-thanos-bucket-replicate.libsonnet, jsonnet/kube-thanos/kube-thanos-receive-router.libsonnet, manifests/thanos-receive-router-deployment.yaml
- `beta.kubernetes.io/os` has been deprecated since [v1.14](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#deprecations). Use the non-beta version instead.
=> Use `kubernetes.io/os` instead of beta version

examples/all/manifests/thanos-compact-serviceMonitor.yaml, examples/all/manifests/thanos-compact-shards-serviceMonitor.yaml, examples/all/manifests/thanos-query-frontend-serviceMonitor.yaml, examples/all/manifests/thanos-query-serviceMonitor.yaml, examples/all/manifests/thanos-receive-hashrings-serviceMonitor.yaml, examples/all/manifests/thanos-receive-serviceMonitor.yaml, examples/all/manifests/thanos-rule-serviceMonitor.yaml, examples/all/manifests/thanos-sidecar-serviceMonitor.yaml, examples/all/manifests/thanos-store-serviceMonitor.yaml, examples/all/manifests/thanos-store-shards-serviceMonitor.yaml, jsonnet/kube-thanos/kube-thanos-compact-shards.libsonnet, jsonnet/kube-thanos/kube-thanos-compact.libsonnet, jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet, jsonnet/kube-thanos/kube-thanos-query.libsonnet, jsonnet/kube-thanos/kube-thanos-receive-hashrings.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, jsonnet/kube-thanos/kube-thanos-rule.libsonnet, jsonnet/kube-thanos/kube-thanos-sidecar.libsonnet, jsonnet/kube-thanos/kube-thanos-store-shards.libsonnet, jsonnet/kube-thanos/kube-thanos-store.libsonnet, manifests/thanos-query-serviceMonitor.yaml, manifests/thanos-receive-ingestor-serviceMonitor.yaml, manifests/thanos-store-serviceMonitor.yaml
The `relabelings` block of the `serviceMonitor` configuration for the query component does not include the `action` field.
The default value for action is `replace`.
- https://github.com/prometheus-operator/prometheus-operator/blob/e2ce57ad6c383a886a7d5fb518a677e1dd6a6115/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml#L179-L189
- https://github.com/prometheus-operator/prometheus-operator/blob/e2ce57ad6c383a886a7d5fb518a677e1dd6a6115/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml#L360-L373
Having this field undefined makes [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) always unsynced. 
The definitions in this repo code lack the `action` field, but when the object is created in Kubernetes, the field is written in the Kubernetes …
=> query: Add support for ArgoCD: Define replace action in servicemonitor

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-query.libsonnet
With this commit we allow configuring the following Thanos query options:
- query.telemetry.request-duration-seconds-quantiles
- query.telemetry.request-samples-quantiles
- query.telemetry.request-series-seconds-quantiles
Note that the jsonnet variable expects a comma seperated list, which will be expanded to the format required by Thanos. As an example the following jsonnet configuration:
```
telemetryDurationQuantiles: '1, 2, 3',
telemetrySamplesQuantiles: '100,1000,10000,100000',
telemetrySeriesQuantiles: '10,100,1000,10000',
```
Will result in the following command line arguments to Thanos
```
--query.telemetry.request-duration-seconds-quantiles=1
--query.telemetry.request-duration-seconds-quantiles=2
--query.telemetry.request-duration-seconds-quantiles=3 …
```
=> Query: Allow configuring telemetry.request options

CHANGELOG.md, examples/all/manifests/thanos-receive-default-statefulSet.yaml, examples/all/manifests/thanos-receive-region-1-statefulSet.yaml, examples/all/manifests/thanos-receive-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet, manifests/thanos-receive-ingestor-default-statefulSet.yaml
Exposes [minReadySeconds](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#minimum-ready-seconds) for the Thanos receive StatefulSet. Keeps default behaviour by setting value to zero.
=> receive: Expose minReadySeconds as config

CHANGELOG.md, jsonnet/kube-thanos/kube-thanos-receive-default-params.libsonnet, jsonnet/kube-thanos/kube-thanos-receive.libsonnet
Add limits-config-file flag to the receive component.
Add receive flag for limits-config-file and volume mount. Followed convention used by alertmanagerConfigFile.
Checked generated json file with the flag, cli arg is generated as well as volume and volumeMount sections.
=> receive: allow configuration of limits-config-file

jsonnet/kube-thanos/kube-thanos-receive.libsonnet
update receive store limits type to  string instead of integer. Having an integer prevents setting arbitrary values in the generated file that can be post-processed (e.g. '${MY_VALUE}').
=> receive: update receive store limits type to  string

CHANGELOG.md, examples/all/manifests/thanos-rule-statefulSet.yaml, jsonnet/kube-thanos/kube-thanos-rule.libsonnet
=> Add Pod anti-affinity to Thanos Rule
